### ISSUE TITLE
Broken weights link

### ISSUE THREAD

**Issue by awarebayes** [thohemp/6DRepNet360#2]
Greetings, I was trying to run test.py, but could not download the model:

```
❯ python test.py
Loading data.
/home/mscherbina/Documents/github_repos/6DRepNet/dataset/AFLW2000/files.txt
Downloading: "https://cloud.ovgu.de/s/jFd5JAacLdAtZ4N/download/6DRepNet360_300W_LP_AFLW2000.pth" to /home/mscherbina/.cache/torch/hub/checkpoints/6DRepNet360_300W_LP_AFLW2000.pth
Traceback (most recent call last):
  File "/home/mscherbina/Documents/github_repos/6DRepNet360/sixdrepnet360/test.py", line 168, in <module>
    saved_state_dict = load_state_dict_from_url(
  File "/home/mscherbina/anaconda3/lib/python3.9/site-packages/torch/hub.py", line 727, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/mscherbina/anaconda3/lib/python3.9/site-packages/torch/hub.py", line 593, in download_url_to_file
    u = urlopen(req)
  File "/home/mscherbina/anaconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mscherbina/anaconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/mscherbina/anaconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/mscherbina/anaconda3/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/mscherbina/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/mscherbina/anaconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found


```

**Comment by awarebayes** [comment]
Could you please update the link?

**Comment by thohemp** [comment]
Link updated. https://github.com/thohemp/6DRepNet360/commit/41bad95f059f66cf881825c5f9abd78edf729941

**Comment by awarebayes** [comment]
Also, do you mind if I ask when this will be open sourced?

**Comment by awarebayes** [comment]
This does not affect the results however, just a sensible thing
